#!/bin/bash
#PBS -l nodes=1:ppn=1,walltime=0:30:00
#PBS -N app--thickness-volume-eccentricity
#PBS -V

# generate thickness and volume files
echo $FREESURFER_LICENSE > license.txt
time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/freesurfer:6.0.0 ./convert.sh

# bin by eccentricity
time singularity exec -e docker://brainlife/mcr:neurodebian1604-r2017a ./compiled/eccentricityVolumeThickness
